In [1]:
import numpy as np

In [17]:
#special matrices
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
2*np.ones((2,3))

array([[2., 2., 2.],
       [2., 2., 2.]])

In [4]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
#arrays with random numbers
np.random.rand() #uniform [0,1)

0.9207320707988005

In [16]:
np.random.rand(2,3) #dimensions instead of tuple, convenience function for porting code from Matlab.

array([[0.28495013, 0.2059507 , 0.04759306],
       [0.15417703, 0.67481479, 0.87184395]])

In [13]:
np.random.randn() #standard nomral

-0.5844111127005696

In [15]:
np.random.randn(2,3) #dimensions instead of tuple, convenience function for porting code from Matlab.

array([[-1.34050321, -0.63017822,  0.77369365],
       [-1.01207196, -0.13872755, -1.11614376]])

In [18]:
# calculating statistics
R = np.random.randn(10000)

In [21]:
R.mean()

np.float64(-0.007377290677998564)

In [22]:
R.var() #default ddof = 0, population variance

np.float64(0.9924537170921165)

In [23]:
R.var(ddof = 1) #sample variance

np.float64(0.9925529723893555)

In [34]:
R.std()

np.float64(0.9962197132621481)

In [43]:
# statistics on random matrices
R = np.random.randn(10000,3)

In [44]:
R.shape #10000 observations * 3 measurements

(10000, 3)

In [46]:
R.mean() #default mean of flattened array

np.float64(-0.013280838676183532)

In [47]:
R.mean(axis=0) #mean over rows, rows disappear

array([-0.02907012,  0.00052358, -0.01129598])

In [53]:
R.mean(axis=1) #mean over columns, columns disappear

array([-0.28573908,  1.25916786, -0.58223081, ...,  0.35627558,
       -0.01324519, -0.68133128], shape=(10000,))

In [52]:
R.mean(axis=1).shape

(10000,)

In [61]:
np.cov(R).shape #default consider rows as variables

(10000, 10000)

In [60]:
np.cov(R.T) #sanity check: close to identity

array([[ 0.98951782, -0.0026016 , -0.00822789],
       [-0.0026016 ,  0.99347561, -0.0074671 ],
       [-0.00822789, -0.0074671 ,  1.00126366]])

In [62]:
np.cov(R, rowvar=False)

array([[ 0.98951782, -0.0026016 , -0.00822789],
       [-0.0026016 ,  0.99347561, -0.0074671 ],
       [-0.00822789, -0.0074671 ,  1.00126366]])

In [67]:
np.cov(R, rowvar=False, ddof=1) #sample cov, unbiased by default

array([[ 0.98951782, -0.0026016 , -0.00822789],
       [-0.0026016 ,  0.99347561, -0.0074671 ],
       [-0.00822789, -0.0074671 ,  1.00126366]])

In [68]:
np.cov(R, rowvar=False, ddof=0) #population cov

array([[ 0.98941887, -0.00260134, -0.00822707],
       [-0.00260134,  0.99337626, -0.00746635],
       [-0.00822707, -0.00746635,  1.00116354]])

In [70]:
help(np.random.randint)

Help on method randint in module numpy.random:

randint(low, high=None, size=None, dtype=<class 'int'>) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)

    Return random integers from `low` (inclusive) to `high` (exclusive).

    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).

    .. note::
        New code should use the `~numpy.random.Generator.integers`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, o

In [75]:
#generate random integers 0-9
np.random.randint(0,10,size=(3,3)) #[0,10) discrete uniform

array([[1, 8, 9],
       [7, 0, 5],
       [5, 8, 0]])

In [72]:
np.random.randint(0,10,size=(3,3))

array([[4, 9, 2],
       [7, 2, 1],
       [4, 2, 2]])

In [80]:
#randomly select item
help(np.random.choice)

Help on method choice in module numpy.random:

choice(a, size=None, replace=True, p=None) method of numpy.random.mtrand.RandomState instance
    choice(a, size=None, replace=True, p=None)

    Generates a random sample from a given 1-D array

    .. note::
        New code should use the `~numpy.random.Generator.choice`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    .. warning::
        This function uses the C-long dtype, which is 32bit on windows
        and otherwise 64bit on 64bit platforms (and 32bit on 32bit ones).
        Since NumPy 2.0, NumPy's default integer is 32bit on 32bit platforms
        and 64bit on 64bit platforms.


    Parameters
    ----------
    a : 1-D array-like or int
        If an ndarray, a random sample is generated from its elements.
        If an int, the random sample is generated as if it were ``np.arange(a)``
    size : int or tuple of ints, optional
        Output shape.  If the 

In [79]:
for i in range(3):
    print(i)

0
1
2


In [82]:
np.arange(3)

array([0, 1, 2])

In [84]:
#generate random integers 0-9
np.random.choice(10,size=(3,3))

array([[4, 9, 8],
       [7, 2, 2],
       [6, 1, 6]])