In [12]:
import numpy as np

In [5]:
# Use list of list to represent matrices
L = [[1,2],
     [3,4]]
L

[[1, 2], [3, 4]]

In [14]:
# first row
L[0]

[1, 2]

In [9]:
# top-right corner element
L[0][1]

2

In [10]:
# second column
# list comprehension
[row[1] for row in L]

[2, 4]

In [16]:
# Use it to create array
A = np.array(L)
A

array([[1, 2],
       [3, 4]])

In [24]:
# first row
A[0]

array([1, 2])

In [18]:
# top-right corner element
A[0][1]

np.int64(2)

In [22]:
# top-right corner element!
A[0,1]

np.int64(2)

In [25]:
# second column!
A[:,1]

array([2, 4])

In [42]:
# transpose
A.T

array([[1, 3],
       [2, 4]])

In [43]:
# determinent
np.linalg.det(A) # using determinant of U in LU decomposition, or R in QR decomposition, so not -2, but -2.....

np.float64(-2.0000000000000004)

In [44]:
# inverse
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [36]:
np.linalg.inv(A).dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [39]:
# trace
A.trace()

np.int64(5)

In [28]:
# element-wise operation
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [45]:
# Numpy stacks all recognize lists as arrays as an input, so no need to worry passing list!
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [30]:
# matrix multiplication
B = np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
# matrix multiplication (as a generalization of dot products)!
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [47]:
# An interesting example of an overloaded function, i.e. multiple functions with the same name but different parameters.
np.diag(A) # get the diagnal vector

array([1, 4])

In [48]:
np.diag([1,4]) # get the matrix with it as diagnal vector

array([[1, 0],
       [0, 4]])

In [51]:
# eigen valuse and eigen vectors
np.linalg.eig(A) #NOTE: eigenvectors are stored as column vectors

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [52]:
Lam, V = np.linalg.eig(A)

In [53]:
Lam

array([-0.37228132,  5.37228132])

In [54]:
V

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

In [59]:
V[:,0]

array([-0.82456484,  0.56576746])

In [57]:
A@V[:,0]

array([ 0.30697009, -0.21062466])

In [58]:
Lam[0]*V[:,0]

array([ 0.30697009, -0.21062466])

In [61]:
Lam[0]*V[:,0] == A@V[:,0] # == works element-wisely for arrays

array([ True, False])

In [66]:
Lam[0]*V[:,0]-A@V[:,0] # sanity check finds arithmetic machine error

array([ 0.00000000e+00, -5.55111512e-17])

In [67]:
# the correct way to compare two arrays equal
np.allclose(Lam[0]*V[:,0],A@V[:,0])

True

In [68]:
help(np.allclose)

Help on _ArrayFunctionDispatcher in module numpy:

allclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False)
    Returns True if two arrays are element-wise equal within a tolerance.

    The tolerance values are positive, typically very small numbers.  The
    relative difference (`rtol` * abs(`b`)) and the absolute difference
    `atol` are added together to compare against the absolute difference
    between `a` and `b`.

    .. warning:: The default `atol` is not appropriate for comparing numbers
                 with magnitudes much smaller than one (see Notes).

    NaNs are treated as equal if they are in the same place and if
    ``equal_nan=True``.  Infs are treated as equal if they are in the same
    place and of the same sign in both arrays.

    Parameters
    ----------
    a, b : array_like
        Input arrays to compare.
    rtol : array_like
        The relative tolerance parameter (see Notes).
    atol : array_like
        The absolute tolerance parameter (see Notes).


In [69]:
# check all eigenvectors at the same time with matrix notation
np.allclose(V@np.diag(Lam), A@V)

True

In [ ]:
#More precisely, for real symmetric or complex hermitian matrices, use np.linalg.eigh, since it use eigen decompostion directly
#This is useful for COV matrix